#!/usr/bin/python
# -*- coding: utf-8 -*-

import sys
import os
import urllib
import tornado.template

def parse_params(str_params):
    params = {}
    elements = str_params.split('&')
    for i in range(len(elements)):
        element = elements[i].split('=', 1)
        params[element[0]] = urllib.unquote_plus(urllib.unquote(element[1]))
    return params

def create_htlm_from_template(templates_dir, template_name, params):
    loader = tornado.template.Loader(templates_dir)
    print loader.load(template_name).generate(**params)

if len(sys.argv) < 2:
    print "No paramters found"
    sys.exit(1)

try:
    params = parse_params(sys.argv[1])
except Exception as e:
    print "Could not parse parameters:"
    print e.message
    sys.exit(1)

try:
    templates_dir = os.path.join(os.path.dirname(os.path.realpath(__file__)), "templates")
    template_name = os.path.splitext(os.path.basename(sys.argv[0]))[0] + ".html"
    create_htlm_from_template(templates_dir, template_name, params)
except Exception as e:
    print "Could not generate html:"
    print e.message
    sys.exit(1)
